// <auto-generated />
namespace Artist.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSection));
        
        string IMigrationMetadata.Id
        {
            get { return "202110201733511_AddSection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
